### ISSUE TITLE
Build error on Ubuntu with LTS 3.20

### ISSUE THREAD

**Issue by varosi** [mikeizbicki/ConstraintKinds#9]
It is used as (direct/indirect) dependency on HLearn and build against LTS-3.20:

Configuring ConstraintKinds-1.1.0.0...
    Building ConstraintKinds-1.1.0.0...
    Preprocessing library ConstraintKinds-1.1.0.0...
    [1 of 9] Compiling Control.ConstraintKinds.Partitionable ( src/Control/ConstraintKinds/Partitionable.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Control/ConstraintKinds/Partitionable.o )
    [2 of 9] Compiling Control.ConstraintKinds.Functor ( src/Control/ConstraintKinds/Functor.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Control/ConstraintKinds/Functor.o )
    [3 of 9] Compiling Control.ConstraintKinds.Pointed ( src/Control/ConstraintKinds/Pointed.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Control/ConstraintKinds/Pointed.o )
    [4 of 9] Compiling Control.ConstraintKinds.Foldable ( src/Control/ConstraintKinds/Foldable.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Control/ConstraintKinds/Foldable.o )
    
    /tmp/stack16346/ConstraintKinds-1.1.0.0/src/Control/ConstraintKinds/Foldable.hs:58:10:
        Ambiguous occurrence ‘Foldable’
        It could refer to either ‘Control.ConstraintKinds.Foldable.Foldable’,
                                 defined at src/Control/ConstraintKinds/Foldable.hs:26:1
                              or ‘P.Foldable’,
                                 imported from ‘Prelude’ at src/Control/ConstraintKinds/Foldable.hs:20:1-36
                                 (and originally defined in ‘Data.Foldable’)
    
    /tmp/stack16346/ConstraintKinds-1.1.0.0/src/Control/ConstraintKinds/Foldable.hs:76:10:
        Ambiguous occurrence ‘Foldable’
        It could refer to either ‘Control.ConstraintKinds.Foldable.Foldable’,
                                 defined at src/Control/ConstraintKinds/Foldable.hs:26:1
                              or ‘P.Foldable’,
                                 imported from ‘Prelude’ at src/Control/ConstraintKinds/Foldable.hs:20:1-36
                                 (and originally defined in ‘Data.Foldable’)
    
    /tmp/stack16346/ConstraintKinds-1.1.0.0/src/Control/ConstraintKinds/Foldable.hs:90:10:
        Ambiguous occurrence ‘Foldable’
        It could refer to either ‘Control.ConstraintKinds.Foldable.Foldable’,
                                 defined at src/Control/ConstraintKinds/Foldable.hs:26:1
                              or ‘P.Foldable’,
                                 imported from ‘Prelude’ at src/Control/ConstraintKinds/Foldable.hs:20:1-36
                                 (and originally defined in ‘Data.Foldable’)
    
    /tmp/stack16346/ConstraintKinds-1.1.0.0/src/Control/ConstraintKinds/Foldable.hs:105:10:
        Ambiguous occurrence ‘Foldable’
        It could refer to either ‘Control.ConstraintKinds.Foldable.Foldable’,
                                 defined at src/Control/ConstraintKinds/Foldable.hs:26:1
                              or ‘P.Foldable’,
                                 imported from ‘Prelude’ at src/Control/ConstraintKinds/Foldable.hs:20:1-36
                                 (and originally defined in ‘Data.Foldable’)

**Comment by feuerbach** [comment]
Just ran into this myself. It's a consequence of #7, which forces cabal to pick an old version of ConstraintKinds to satisfy the dependency.
